# Generated by Django 5.1.1 on 2024-09-12 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Moihik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zapisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('МОЙКА КУЗОВА', 'Мойка кузова'), ('ПОЛИРОВКА', 'Полировка'), ('ХИМЧИСТКА САЛОНА', 'Химчистка салона'), ('НАНЕСЕНИЕ ВОСКА', 'Нанесение воска'), ('УДАЛЕНИЕ РЕАГЕНТА', 'Удаление реагента'), ('КОМПЛЕКСНАЯ МОЙКА', 'Комплексная мойка'), ('ЧЕРНЕНИЕ РЕЗИНЫ', 'Чернение резины')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('moihik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.moihik')),
            ],
        ),
    ]
